### ISSUE TITLE
App Crashed in Android device when detecting Plane in react-viro

### ISSUE THREAD

**Issue by Sandeep155Vibhuti** [NativeVision/viro#30] opened 2021-06-29 06:21 UTC
## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: What Android OS version (11.0, etc.) is your device running on?
3. Version: ViroReact version - 2.20.2 & React Native version - 0.64.2
4. Device(s): What device(s) are you are seeing the issue on (i.e. Samsung Galaxy M30s etc)

## Description
Inside My RN App when App Started and Camera Opened and Device Detecting the Surface some it can Shows the Plane White and after that App Crashed here are the Logs After the App Crashed in Android Studio
### Please Provide the Solve if Anyone Else Facing this Issue

![Screenshot 2021-06-29 at 11 46 31 AM](https://user-images.githubusercontent.com/75908175/123746901-de0a9f00-d8cf-11eb-88b3-73faf2da5bc0.png)
![Screenshot 2021-06-29 at 11 47 50 AM](https://user-images.githubusercontent.com/75908175/123746964-ee227e80-d8cf-11eb-92e8-b7d0c04a35e8.png)

**Comment by saeedtkh** [comment] 2021-12-09 12:35
any updates?

**Comment by NS-BOBBY-C** [comment] 2021-12-18 18:57
Can you help us provide a reproduceable demo? I'll gladly accept PR's to the repo I use to diagnose things https://github.com/NS-BOBBY-C/starter-kit

**Comment by robertjcolley** [comment] 2024-01-29 22:08
Closing due to no answer

**Closed by robertjcolley** 2024-01-29 22:08 UTC
Labels: bug, question
